### ISSUE TITLE
Staking explorer - UI bug when collecting reward

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2225]
**Describe the bug**
After the transaction has been signed, there is a popup that shows the amount of reward claimed, that amount is currently 0 ONES

**To Reproduce**
1. Claim reward using the staking explorer

note : signature is done with the Harmony chrome extenion

**Expected behavior**
Correct amount claimed

**Screenshots**
https://imgur.com/a/t3yyRaa

**Environment (please complete the following information):**
 - OS: [Win10]

**Additional context**
N/A

**Comment by mikedoan** [comment]
we fixed a bug yesterday - it should be fixed now

**Comment by mindstyle85** [comment]
still not fixed, besides showing amount 0, when prompted to confirm the transaction/withdrawal with password, it doesnt show any info about what is being confirmed (no amount, nothing)

![scr](https://user-images.githubusercontent.com/55639830/75501496-75a46880-59d0-11ea-9b6f-84ddef3b40a0.png)

**Comment by mikedoan** [comment]
<img width="1244" alt="Screen Shot 2020-02-27 at 5 45 03 PM" src="https://user-images.githubusercontent.com/40258599/75502912-12dbae80-5989-11ea-8425-37572648d175.png">
<img width="1232" alt="Screen Shot 2020-02-27 at 5 45 15 PM" src="https://user-images.githubusercontent.com/40258599/75502915-15d69f00-5989-11ea-8827-dee1e5123048.png">
<img width="1245" alt="Screen Shot 2020-02-27 at 5 45 36 PM" src="https://user-images.githubusercontent.com/40258599/75502921-18d18f80-5989-11ea-9699-835c631df3d3.png">


have you installed the new extension in the doc? here what i got
@sophoah

**Comment by mikedoan** [comment]
I marked it fixed again. please mark not fixed if you get it again. maybe DM me

**Comment by mindstyle85** [comment]
@mikedoan sorry missed that the new extension is only via the build.zip file, i just installed it from the extension list.. 

confirmed working with the new version from build.zip!

**Comment by sophoah** [comment]
@mikedoan confirmed it worked as well, small note though the loaded extension shows 0.0.1 as the version. Good job. Closing the issue.

**Comment by mindstyle85** [comment]
shows 0 again in the latest version of extension for both me and @sophoah (i downloaded and built mine 30min ago)

**Comment by sophoah** [comment]
@mikedoan looks like intermittent at first but did more test, and looks like for small reward, no issue, but when reward are bigger it would show 0 (tested with 1k 2k) and @mindstyle85 alsoc onfirmed

**Comment by BrunoMarshall** [comment]
I´m performing tests with different amount "collect rewards"
- for 6.6 rewards appears the pop-up message confirmation with the value 
![image](https://user-images.githubusercontent.com/35432495/75622531-86f09f00-5ba1-11ea-81e5-dd09edae8a75.png)

-for 1034 i got the issue:
![image](https://user-images.githubusercontent.com/35432495/75622624-cf5c8c80-5ba2-11ea-8c8d-837a215e1ad2.png)

- for 39390 rewards the pop-up message don´t appears, the confirmation appears in the window
![image](https://user-images.githubusercontent.com/35432495/75622552-cc14d100-5ba1-11ea-8b89-6b2ed4e04c58.png)

**Comment by yelllowsin** [comment]
@mikedoan I can confirm it works for small amounts, but when the claimed reward get's bigger it shows as 0 on the screen, though the rewards are claimed succesfully. Tested claiming 1.5 ONE (shows correctly the amount) and tested claiming 5000 ONE (shows 0 on the screen).

Using Harmony extensions version: 0.0.1

**Comment by mikedoan** [comment]
![image](https://user-images.githubusercontent.com/40258599/77708041-29732680-6f84-11ea-8786-5dbcf15190ec.png)

**Comment by mikedoan** [comment]
i tested and did not get any zero - 

also FYI, the reward amount may be different from the reward you saw before claiming rewards because the rewards get increased in every epoch.

**Comment by mikedoan** [comment]
@yelllowsin maybe you dm-ed to test together

**Comment by yelllowsin** [comment]
@mikedoan i have just tested claiming 4000 ONE's and it still shows as zero. If you claim with small amounts like 7 ONES it works.

![image](https://user-images.githubusercontent.com/7217595/77708215-39036700-6fa6-11ea-9e00-8a564dfcf540.png)

**Comment by yelllowsin** [comment]
@mikedoan sure, i can DM you on Discord. For me to replicate this i would have to wait a bit more to gather more than 1000 ONE's. It shouldn't take longer.

**Comment by BrunoMarshall** [comment]
Hi all, collected today more >15000, same error:
if you see my previous message i´m assuming that the error accours with >1000
![image](https://user-images.githubusercontent.com/35432495/77738996-178b9500-7011-11ea-8ce9-5d8e6e482f23.png)

**Comment by sophoah** [comment]
@mikedoan yeah same

before : 
![image](https://user-images.githubusercontent.com/35721420/77740246-de254a80-704d-11ea-830f-219e228093e8.png)

claim the 1000+ woud show with 0 : 
![image](https://user-images.githubusercontent.com/35721420/77740313-fb5a1900-704d-11ea-8345-1d80c6f09a6d.png)

and claim again when it is still below 1000 will work: 
![image](https://user-images.githubusercontent.com/35721420/77740399-25134000-704e-11ea-8fda-855ad59789b4.png)

**Comment by mikedoan** [comment]
I got it now - we are working on fixing. this.

**Comment by mikedoan** [comment]
It should be a bug in chrome extension - I believe you got. the rewards but
it just showed 0. a fix is coming soon

**Comment by mikedoan** [comment]
fixed and tested with @yelllowsin 

now we should use the new one at https://github.com/harmony-one/staking-dashboard/tree/master/extension_versions
