### ISSUE TITLE
Can't kill the node with CTRL+C

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2264]
**Describe the bug**
Node can't or quite difficult to kill / stop

When trying to CTRL+C here are the messages:
```
./node.sh -k bls100.key -N staking -z -D -S
node.sh: using manually specified BLS key file: bls100.key
node.sh: binaries did not change
node.sh: public IP address autodetected: ip
Enter passphrase for the BLS key file bls100.key:
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 3c2d2845ca8701f35def6879576d3261d89959ed878ce5d1fe9b9943d6b6228489c9482bbc9f2f75d17a82a83f8ec609 -> shard 2
^CGot interrupt signal. Dumping state to DB...
^CGot interrupt signal. Dumping state to DB...
^CGot interrupt signal. Dumping state to DB...
^CGot interrupt signal. Dumping state to DB...
^CGot interrupt signal. Dumping state to DB...
```

from the main terminal, after doing pkill harmony, this appears in node windows : 
```
Got terminated signal. Gracefully shutting down...
```

for quite a while ... and can be finally be killed with a kill -9
```
root@vmi334486:~/harmony# ps aux | grep harmony
root     25729 12.1  1.1 4356840 183336 pts/2  Sl+  13:53   2:59 ./harmony -bootnodes /ip4/54.86.126.90/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/52.40.84.2/tcp/9867/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29 -ip 173.212.232.90 -port 9000 -is_genesis -network_type=testnet -dns_zone=os.hmny.io -blacklist=./.hmy/blacklist.txt -is_archival=false -blskey_file bls100.key -shard_id=-1 -staking=true -blspass stdin
root     27164  0.0  0.0   6364   980 pts/0    S+   14:17   0:00 grep --color=auto harmony
root@vmi334486:~/harmony# pkill harmony
root@vmi334486:~/harmony# ps aux | grep harmony
root     25729 12.1  1.1 4356840 183336 pts/2  Sl+  13:53   3:00 ./harmony -bootnodes /ip4/54.86.126.90/tcp/9867/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv,/ip4/52.40.84.2/tcp/9867/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29 -ip 173.212.232.90 -port 9000 -is_genesis -network_type=testnet -dns_zone=os.hmny.io -blacklist=./.hmy/blacklist.txt -is_archival=false -blskey_file bls100.key -shard_id=-1 -staking=true -blspass stdin
root     27173  0.0  0.0   6364   980 pts/0    R+   14:18   0:00 grep --color=auto harmony
root@vmi334486:~/harmony# kill -9 25729
root@vmi334486:~/harmony# ps aux | grep harmony
root     27181  0.0  0.0   6364   848 pts/0    R+   14:18   0:00 grep --color=auto harmony
root@vmi334486:~/harmony#
```

**To Reproduce**
1. run the custom build harmony
2. stop the node via CTRL+C

Note since current node.sh doesn't allow us to download the binary we are using a custom build harmony binary : 
```
bash <(curl -sSL https://raw.githubusercontent.com/SebastianJ/harmony-tools/master/install/install.sh) 
```

**Expected behavior**
CTRL+C should directly stop the node

**Screenshots**
N/A

**Environment (please complete the following information):**
- Ubuntu 18
- harmony version : 
```root@vmi334486:~/harmony# ./harmony --version
Harmony (C) 2020. harmony, version v5563-master-20191208.0-186-g0407e767 (deploy@ 2020-02-13T05:58:06+0100)
```
- Go environment [ ```go env``` ]

**Additional context**

**Comment by sophoah** [comment]
@denniswon seeing you are working on https://github.com/harmony-one/harmony/pull/2244 does that mean we have to live with slow CTRL+C ?

**Comment by BrunoMarshall** [comment]
I have recreated your issue @sophoah .  effectively i could not kill the node with crtl+c
here is the picture after press two times:
 
![image](https://user-images.githubusercontent.com/35432495/74459174-27994c00-4e8b-11ea-9073-8b329692c056.png)

**Comment by john-harmony** [comment]
HI,
Currently you can use CTRL+z

**Comment by sophoah** [comment]
@john-harmony ok so the only way to kill the node is through kill -9 like how i mentioned in the issue. Could that cause DB corruption error since I understand this graceful shutdown has been implemented for state pruning?

**Comment by mindstyle85** [comment]
@sophoah this one is fixed now

**Comment by mindstyle85** [comment]
scratch that, not fixed:

node.sh: ############### Running Harmony Process ###############
Staking mode; node key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 -> shard 2
^CGot interrupt signal. Gracefully shutting down...
^[[A^[[A^C^C^C^C^C^C^C

**Comment by mindstyle85** [comment]
the node still hangs here for me if i try ctrl+c

**Comment by BrunoMarshall** [comment]
I´m still have issues to stop the node with Ctr+c
i need to use the ctr+z stated above

**Comment by BrunoMarshall** [comment]
![image](https://user-images.githubusercontent.com/35432495/74853422-345fe900-533e-11ea-8c6c-080d807a755e.png)

**Comment by rlan35** [comment]
This should have been fixed. Can @BrunoMarshall retest it? Thanks.

**Comment by mindstyle85** [comment]
@rlan35 still doesnt work:

Staking mode; node key e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 -> shard 2
^CGot interrupt signal. Gracefully shutting down...
^Z
[5]+  Stopped                 sudo ./node.sh -k e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116.key -z -N staking -D

note that i wait 2-3min before stopping with ctrl z since it just hanged with  that gracefully shutting down message

**Comment by Cem-Harmony** [comment]
I interrupted the node with ctrl-c, the node shut down, and I was able to start it back up with no errors.
```
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 0a0dc9c7e9f608dabbba96040ea0a1119fcb491a0af55158ca5c94bf355859a0da3e511aee3538f75e54a9cd7b5cfb08 -> shard 0
^CGot interrupt signal. Gracefully shutting down...
Successfully shut down!
node.sh: received SIGINT
node.sh: terminating update checker (pid 3456)
```

**Comment by mindstyle85** [comment]
confirmed working with last 2 versions (26th and 27th feb)
