### ISSUE TITLE
created validator without an actual confirmation

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2348]
**Describe the bug**

I tried creating a validator on my 2nd address, ran the command and got back insufficient funds (i forgot i depleted s0 funds on it). So i sent some funds from the same address on s1->s0, waited a bit and tried again, this is what i got:

luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea --details "pink pony node runners2" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 10000 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 1000 --chain-id testnet
Enter the bls passphrase:
[CreateValidator] insufficient balance to stake -- 2020-02-29 21:33:42 +0100 CET
commit: v300-d6ddd06, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag

luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q --name mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea --details "pink pony node runners2" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 10000 --bls-pubkeys 1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12 --amount 1000 --chain-id testnet
Enter the bls passphrase:
[CreateValidator] one1675d7adqu9egn0ehd9fx4f6jmdjfynw3gkr48q: staking validator already exists -- 2020-02-29 21:36:34 +0100 CET
commit: v300-d6ddd06, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
luka@ubuntu:~/Desktop/devnet2$ 

might not be an issue, but is it possible the first of these commands actually went through? Meaning that at the time i pressed enter i didnt fund my s0 balance yet, but before i tried the second time it got funded and the first create validator tx went through?

**Comment by Daniel-VDM** [comment]
Were you able to create a validator after a little while?

**Comment by mindstyle85** [comment]
the validator actually got created with one of the above two commands, it is in the comittee and i didnt try it again. I had the same thing with Nick V whom i helped creating the validator. He has ran the commnand before i managed to fund his account but the end result was still a created validator (his is John) - so looks like one of these txs actually goes through even if it at first says not enough balance (because the tx sent to fund the account comes in somehwere in between).

Pretty easy to test/confirm, just have an empty account, send some funds to it, but as soon as you send do the create validator command once or twice (should return no funds), but when the funds arrive, on of these actually seems to still create it.

**Comment by sophoah** [comment]
I managed to recreate the issue

So in short, the bug here is the fact that we don't have a successful message ever in that scenario though at the end the validator is actually created successfully

Scenario is :
1 - to try to create a failed validator (not sufficient amount)
2 - transfer the sufficient amount for the actual creation
3 - create the validator

See capture: 
this is step 1 where I didn't have enough fund in shard 0 on Mon 02 Mar 2020 02:44:29 PM UTC
```
date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:44:29 PM UTC
Enter the bls passphrase:
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:44:31 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
```
step 2, doing the fund transfer
```
date && ./hmy --node="https://api.s0.os.hmny.io" transfer --from-shard 1 --to-shard 0 --from one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh  --to one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --amount 40
Mon 02 Mar 2020 02:44:58 PM UTC
{
  "transaction-hash": "0xdd5d50d5623a4b02ddd3b306620b6f216261ab60fb98ec883e756bdef0ee0fcd",
  "blockchain-receipt": {
    "blockHash": "0xd5d57cafacede647ce91282a27f9370d1d798838675c65b8bcb07648927df093",
    "blockNumber": "0x71d1",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "from": "one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "shardID": 1,
    "status": "0x1",
    "to": "one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh",
    "transactionHash": "0xdd5d50d5623a4b02ddd3b306620b6f216261ab60fb98ec883e756bdef0ee0fcd",
    "transactionIndex": "0x0"
  },
  "time-signed-utc": "2020-03-02 14:45:01.091578"
}
```
see above time signed 

and 3, trying a few times to create the validator with the same information that always failed with the same error until the 5th time where error message is different (ie validator is already created), so one of the first 4th actually went through.
```
root@vmi334486:~/harmony# date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:45:08 PM UTC
Enter the bls passphrase:
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:44:31 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:11 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
root@vmi334486:~/harmony# date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:45:25 PM UTC
Enter the bls passphrase:

[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:44:31 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:11 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:28 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
root@vmi334486:~/harmony#
root@vmi334486:~/harmony# date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:45:41 PM UTC
Enter the bls passphrase:
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:44:31 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:11 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:28 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:43 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
root@vmi334486:~/harmony# date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:47:34 PM UTC
Enter the bls passphrase:

[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:44:31 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:11 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:28 +0000 UTC
[CreateValidator] insufficient funds for gas * price + value -- 2020-03-02 14:45:43 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
root@vmi334486:~/harmony#
root@vmi334486:~/harmony# date && echo "" | ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh --name Soph2 --identity Soph2 --website Soph2.harmony.one --security-contact Soph2 --details "Soph2 P-OPS validator" --rate 0.05 --max-rate 0.8 --max-change-rate 0.02 --min-self-delegation 10 --max-total-delegation 100 --bls-pubkeys 7a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018 --amount 30 --chain-id testnet
Mon 02 Mar 2020 02:49:14 PM UTC
Enter the bls passphrase:

[CreateValidator] one15dx98p7zxnjz4e8xft2at7r02ux2mqflyz8vsh: staking validator already exists -- 2020-03-02 14:49:16 +0000 UTC
commit: v295-abda494, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
root@vmi334486:~/harmony#
```

**Comment by Daniel-VDM** [comment]
Ah, we don't flush the error sink if a successful tx went through. I'm going to have to change the error sink logic a bit to account for this.

**Comment by BrunoMarshall** [comment]
This issue happens again Version-v5656-master

1.- tried to create validator without fund

2.-Got error message

3.- Recieved 10000

4.- Tried to create validator:
![image](https://user-images.githubusercontent.com/35432495/76320430-fae92080-62e0-11ea-879e-ba6bb763fa53.png)
5. - validator created even with showing wrong message

**Comment by mindstyle85** [comment]
> Ah, we don't flush the error sink if a successful tx went through. I'm going to have to change the error sink logic a bit to account for this.

i didnt retry this yet, has it been changed?

**Comment by BrunoMarshall** [comment]
This issue happened again, here is the feedback from "K90E" community member
"I tried it once and got: [CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-03-27 04:16:58 +0000 UTC
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-03-27 04:22:08 +0000 UTC
commit: v333-80a4f42, error: staking transaction error
tried it again and got: [CreateValidator] one17acwjm0awk5v47n3yxzz2hvvdddtkwrnelhgav: staking validator already exists -- 2020-03-27 04:31:02 +0000 UTC
commit: v333-80a4f42, error: staking transaction error
so never received the confirmation""

and the validator is created and elected now

**Comment by sophoah** [comment]
the issue is fixed in ``` ./harmony --version
Harmony (C) 2020. harmony, version v5797-v1.3.5-106-g56d19d2a (jenkins@ 2020-04-04T01:23:16+0000)```

creating a staking tx error:
```
./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf --name "Soph Normal Validator node" --identity Soph --website soph.harmony.one --security-contact Soph --details "Soph normal Validator node" --rate 0.1 --max-rate 1 --max-change-rate 0.05 --min-self-delegation 10000 --max-total-delegation 10000000000 --bls-pubkeys  00d69ce5ccd22318af8d0eaee58b04aadd6f55cd7c728b1a45b1620aa6044b22f29d809a17554d0fde4e6bcdefe49e97,2fb1832b89450c8f6cf78ea4075aea489059f43a5b4cee418d8e30675238235ef6aab40219e7933bf827cbe14d18230b,84ad0dc35bdb6ab51c70d7f65a38b1e5230fe451fa895938749c1732c109f6fac7e4107ae44961ef1280c96dedcc3e13,db66379230ed5b875d7f71b98c922a43c1d2a93a65013badaa2cca1a35ace401d37cf81ee54db02be961593ca535b507 --amount 1184680
Enter the bls passphrase:
Enter the bls passphrase:
Enter the bls passphrase:
Enter the bls passphrase:
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 05:52:21 +0000 UTC
commit: v321-2c589a6, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
```
fixing it:
```
 ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf --name "Soph Normal Validator node" --identity Soph --website soph.harmony.one --security-contact Soph --details "Soph normal Validator node" --rate 0.1 --max-rate 1 --max-change-rate 0.05 --min-self-delegation 10000 --max-total-delegation 10000000000 --bls-pubkeys  00d69ce5ccd22318af8d0eaee58b04aadd6f55cd7c728b1a45b1620aa6044b22f29d809a17554d0fde4e6bcdefe49e97,2fb1832b89450c8f6cf78ea4075aea489059f43a5b4cee418d8e30675238235ef6aab40219e7933bf827cbe14d18230b,84ad0dc35bdb6ab51c70d7f65a38b1e5230fe451fa895938749c1732c109f6fac7e4107ae44961ef1280c96dedcc3e13,db66379230ed5b875d7f71b98c922a43c1d2a93a65013badaa2cca1a35ace401d37cf81ee54db02be961593ca535b507 --amount 1184679
Enter the bls passphrase:
Enter the bls passphrase:
Enter the bls passphrase:
Enter the bls passphrase:
{
  "id": "15",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xdc2d17cda5e2b20f9e33ab7438f7ed336358b39ac1468c06f8f6dd1b54acf25a",
    "blockNumber": "0x80e",
    "contractAddress": null,
    "cumulativeGasUsed": "0x51a694",
    "gasUsed": "0x51a694",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "sender": "one1t4p6x5k7zw59kers7hwmjh3kymj0n6spr02qnf",
    "status": "0x1",
    "transactionHash": "0xe35b99aaee05b04ce1c4124638e8fa76ba141aa558bea5a11815829405614901",
    "transactionIndex": "0x0",
    "type": 0
  }
}
```

**Comment by mindstyle85** [comment]
so this still happens:

so i strted creating validator when i had 0 balance, then ive sent funds to the address and did some more creations, below are all responses. However my validator still got created and hmy didnt even error message me that the validator already exists now:

so 2 issues here now:
- no validator creation confirmation
- no error message that validator already exists

Also note that which each try i get one more error message about insufficient funds (bolded below).

luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name "mindstyle #P-OPS" --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.05 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 100000 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1180000 --chain-id pangaea
Enter the bls passphrase:
**[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:04:57 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:10 +0200 CEST**
commit: v352-eaa4d2a, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name "mindstyle #P-OPS" --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.05 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 100000 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1180000 --chain-id pangaea
Enter the bls passphrase:
**[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:04:57 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:10 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:21 +0200 CEST**
commit: v352-eaa4d2a, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name "mindstyle #P-OPS" --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.05 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 100000 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1180000 --chain-id pangaea
Enter the bls passphrase:
**[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:04:57 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:10 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:21 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:34 +0200 CEST**
commit: v352-eaa4d2a, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name "mindstyle #P-OPS" --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.05 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 100000 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1180000 --chain-id pangaea
Enter the bls passphrase:
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:04:57 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:10 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:21 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:34 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:10:20 +0200 CEST
commit: v352-eaa4d2a, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
luka@ubuntu:~/Desktop/devnet2$ ./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name "mindstyle #P-OPS" --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.05 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 100000 --max-total-delegation 1000000000000000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 1180000 --chain-id pangaea
Enter the bls passphrase:
**[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:04:57 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:10 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:21 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:05:34 +0200 CEST
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:10:20 +0200 CEST**
[CreateValidator] current shard-id: 0: insufficient funds for gas * price + value -- 2020-04-04 14:10:30 +0200 CEST
commit: v352-eaa4d2a, error: staking transaction error
check hmy cookbook for valid examples or try adding a `--help` flag
