### ISSUE TITLE
Earned reward per bls key shows 0

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2680]
**Describe the bug**
new feature has been implemented in the latest harmony version ```version v5782-v1.3.5-91-g7b970bae```

however it looks like it doesn't work in OSTN as the earned reward in validator information show 0
```json
./hmy -n https://api.s0.os.hmny.io blockchain validator information one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 161,
        "current-epoch-signing-percentage": "0.706140350877192982",
        "current-epoch-to-sign": 228,
        "num-beacon-blocks-until-next-epoch": 8
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "lifetime": {
      "apr": "16.832999727626356598",
      "blocks": {
        "signed": 349,
        "to-sign": 532
      },
      "reward-accumulated": 302174340873843500000
    },
    "metrics": {
      "by-bls-key": [
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "dfca9b0bb41a358023b75136f51882e2b5396806f4287a0200f772c2b7b8a5981730fbc7558b086da8217969518d3498",
            "earning-account": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
            "effective-stake": "233750000000000000000000.000000000000000000",
            "group-percent": "0.030797101449275362",
            "overall-percent": "0.009855072463768116",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "62937063063c3c8390c86fd406b3155158fe8ecf1e82b0116e1e27cd8fb021c61c39469658d212cb89168ada8ab89a08",
            "earning-account": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
            "effective-stake": "233750000000000000000000.000000000000000000",
            "group-percent": "0.030797101449275362",
            "overall-percent": "0.009855072463768116",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "356b0732524bdd3a2ac6f2a09aa29da9a71b73167f42c64e5ba2b3322d82f79ade31b56efe61782f25c354c1dec28f88",
            "earning-account": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
            "effective-stake": "233750000000000000000000.000000000000000000",
            "group-percent": "0.030797101449275362",
            "overall-percent": "0.009855072463768116",
            "shard-id": 0
          }
        },
        {
```

**To Reproduce**
1. `./hmy -n https://api.s0.os.hmny.io blockchain validator information [VALIDATOR-ADD]`

**Expected behavior**
reward should be different than 0

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by fxfactorial** [comment]
Yep, should be fixed https://github.com/harmony-one/harmony/pull/2681 basically I forgot to remove a `!`. Could be in tomorrow's rolling update

**Comment by mindstyle85** [comment]
this one is still present in current version:

`./hmy blockchain validator information one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --node="https://api.s0.os.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-signed": 298,
        "current-epoch-signing-percentage": "0.801075268817204301",
        "current-epoch-to-sign": 372,
        "num-beacon-blocks-until-next-epoch": 16
      }
    },
    "currently-in-committee": true,
    "epos-status": "currently elected",
    "lifetime": {
      "apr": "0.000000000000000000",
      "blocks": {
        "signed": 1207,
        "to-sign": 1544
      },
      "reward-accumulated": 1.3738515517670726e+21
    },
    "metrics": {
      "by-bls-key": [
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "87cabb98a307eec7a0ff4c9384f28a17e477dac07479f384764ed7687239d034facd98f5fe85133f35bbc3d628e50a18",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.045945945945945946",
            "overall-percent": "0.014702702702702703",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "b1bfc485e0a643dd332a7780cd31e5f28a817e62804439a036a5ff4c5ab49f0976cfafc84c4777e90d19e99a118c7214",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.045945945945945946",
            "overall-percent": "0.014702702702702703",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "5c4c1244a9168afc2e64572250ef426346f5404443f077be5e7493ba942bafb411beca67d4865d554f264ca81b995880",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.045945945945945946",
            "overall-percent": "0.014702702702702703",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 2572972972972975600,
          "key": {
            "bls-public-key": "f66c17c121f2d0d6e1f361af14bd9f481b0eb6b758ef3ee57383560d49b976a8b9e885ffda49c28ae5d9cb067b493d00",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.045945945945945946",
            "overall-percent": "0.014702702702702718",
            "shard-id": 0
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "4ee50030f8f372bc2e605ed20a5c80ad877e65f8d566f0d725c3fc0cc0a9fb67562785731d2585b3603b189a603ffc8d",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.042079207920792079",
            "overall-percent": "0.013465346534653465",
            "shard-id": 1
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "c221b753a0411f6de095610e4dcbf1be1788821973bb5b506ff4956e9b9b60cf331f83ba1dc40ddc17ef25e107bdfb0d",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.042079207920792079",
            "overall-percent": "0.013465346534653465",
            "shard-id": 1
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "65548d2a749327506a910a7307cf770770854ef57874c89b182cdf49ace0321da2c262837e212eee28bc236d5fa3f289",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.042079207920792079",
            "overall-percent": "0.013465346534653483",
            "shard-id": 1
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "146fd89c9cd2f4c3b30cafc3c0fc7aae8cb3ab951b1f7008f1d5eaede2b5699d6979f42196f10e2760b9fc81c1482901",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.042079207920792079",
            "overall-percent": "0.013465346534653465",
            "shard-id": 1
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "4573d93d7cfd364cc2aebb21184e5d8fe92d44e86cd4d13b7e8b25faa77782f3ba6dee0a4e1f65947ea35cabbc552682",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.049562682215743440",
            "overall-percent": "0.015860058309037901",
            "shard-id": 2
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.049562682215743440",
            "overall-percent": "0.015860058309037901",
            "shard-id": 2
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "a11bb4202ecad06799b50dd04f5c2ec631bf411789ade7e62237f698ad3a17dfa90b60354f153404d3886e753f622086",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.049562682215743440",
            "overall-percent": "0.015860058309037901",
            "shard-id": 2
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.049562682215743440",
            "overall-percent": "0.015860058309037901",
            "shard-id": 2
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "7c8ccbdcb1a3c57750c47782b1cd95f51271a062ccb4e70a55a68cd8f0579ddc14c77d6656cb98297186aadea7cf3507",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.052147239263803681",
            "overall-percent": "0.016687116564417178",
            "shard-id": 3
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "5263342d8bbc94fb44cd70b1c2a0948c3b1b39095bc3694b1fa60977c2d519dd62a7fc54895b4e5eb0601a0e425e4493",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.052147239263803681",
            "overall-percent": "0.016687116564417178",
            "shard-id": 3
          }
        },
        {
          "earned-reward": 119774749070366600000,
          "key": {
            "bls-public-key": "868371e59709276ad5f513652e56cc922a03525d2b3af25970436df703617d89a8d6257fe589e20c8555e4537408398b",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.052147239263803681",
            "overall-percent": "0.016687116564417199",
            "shard-id": 3
          }
        },
        {
          "earned-reward": 0,
          "key": {
            "bls-public-key": "7672d516fdf4d5eabe9fb85f9a00042876426cb3505b2ac3d8a1c62d419456c883dac447f304eba74aab456eaac62e8f",
            "earning-account": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
            "effective-stake": "113900000000000000000000.000000000000000000",
            "group-percent": "0.052147239263803681",
            "overall-percent": "0.016687116564417178",
            "shard-id": 3
          }
        }
      ],
      "total-effective-stake": "1822400000000000000000000.000000000000000000"
    },
    "total-delegation": 1.18e+24,
    "validator": {
      "address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
      "bls-public-keys": [
        "e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116",
        "1c57c3282714e412d974a5c1c5712f1f6062d3253d9a080580abf4342805e3311c19f81bef5b1a903fe282650b767a12",
        "4573d93d7cfd364cc2aebb21184e5d8fe92d44e86cd4d13b7e8b25faa77782f3ba6dee0a4e1f65947ea35cabbc552682",
        "a11bb4202ecad06799b50dd04f5c2ec631bf411789ade7e62237f698ad3a17dfa90b60354f153404d3886e753f622086",
        "5c4c1244a9168afc2e64572250ef426346f5404443f077be5e7493ba942bafb411beca67d4865d554f264ca81b995880",
        "87cabb98a307eec7a0ff4c9384f28a17e477dac07479f384764ed7687239d034facd98f5fe85133f35bbc3d628e50a18",
        "b1bfc485e0a643dd332a7780cd31e5f28a817e62804439a036a5ff4c5ab49f0976cfafc84c4777e90d19e99a118c7214",
        "f66c17c121f2d0d6e1f361af14bd9f481b0eb6b758ef3ee57383560d49b976a8b9e885ffda49c28ae5d9cb067b493d00",
        "7c8ccbdcb1a3c57750c47782b1cd95f51271a062ccb4e70a55a68cd8f0579ddc14c77d6656cb98297186aadea7cf3507",
        "7672d516fdf4d5eabe9fb85f9a00042876426cb3505b2ac3d8a1c62d419456c883dac447f304eba74aab456eaac62e8f",
        "5263342d8bbc94fb44cd70b1c2a0948c3b1b39095bc3694b1fa60977c2d519dd62a7fc54895b4e5eb0601a0e425e4493",
        "868371e59709276ad5f513652e56cc922a03525d2b3af25970436df703617d89a8d6257fe589e20c8555e4537408398b",
        "c221b753a0411f6de095610e4dcbf1be1788821973bb5b506ff4956e9b9b60cf331f83ba1dc40ddc17ef25e107bdfb0d",
        "4ee50030f8f372bc2e605ed20a5c80ad877e65f8d566f0d725c3fc0cc0a9fb67562785731d2585b3603b189a603ffc8d",
        "146fd89c9cd2f4c3b30cafc3c0fc7aae8cb3ab951b1f7008f1d5eaede2b5699d6979f42196f10e2760b9fc81c1482901",
        "65548d2a749327506a910a7307cf770770854ef57874c89b182cdf49ace0321da2c262837e212eee28bc236d5fa3f289"
      ],
      "creation-height": 1141,
      "delegations": [
        {
          "amount": 1.18e+24,
          "delegator-address": "one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy",
          "reward": 1.3738515517670726e+21,
          "undelegations": []
        }
      ],
      "details": "pink pony node runners",
      "identity": "mind",
      "last-epoch-in-committee": 33,
      "max-change-rate": "0.050000000000000000",
      "max-rate": "0.500000000000000000",
      "max-total-delegation": 1e+33,
      "min-self-delegation": 1e+23,
      "name": "COVID-21 vaccine mega node by mindstyle #P-OPS",
      "rate": "0.050000000000000000",
      "security-contact": "mamapangaea",
      "update-height": 1141,
      "website": "mind@harmony.one"
    }
  }
}
`

**Comment by danbedford** [comment]
I'm seeing the same thing; 2 keys out of 16 are showing value, the rest are at 0

**Comment by fxfactorial** [comment]
Right it’s present on some but not others. Not clear if it is core protocol issue or multibls issue , @gupadhyaya can investigate

**Comment by fxfactorial** [comment]
should be fixed in https://github.com/harmony-one/harmony/pull/2693
